#This file is basically generated by ChatGPT
#!/usr/bin/env zsh

EXEC_SYMBOLIC=./build/release/test_symbolic
EXEC_CHOLESKY=./build/release/test_cholesky
EXEC_NS=./build/release/test_NS
EXEC_NS_CHOL=./build/release/test_navier_stokes_cholesky

OUT_SYMBOLIC=sparsity_results.csv
OUT_CHOLESKY=cholesky_timings.csv
OUT_NS=NS_timings.csv

START=2
END=20

RUNS=5  # number of repetitions for averaging

echo "subdiv,n,P_nnz,L_nnz,L_D_nnz" > $OUT_SYMBOLIC
echo "subdiv,n,chol_time_avg,chol_nested_time_avg" > $OUT_CHOLESKY
echo "subdiv,ns_time_avg,cholesky_time_avg" > $OUT_NS

for s in {$START..$END}; do
    echo "Running subdiv=$s"

    ############################################################
    # SYMBOLIC TEST (no timing needed)
    ############################################################
    symbolic_output=$($EXEC_SYMBOLIC -s $s)

    subdiv=$(echo "$symbolic_output" | awk '/subdiv:/ {print $2}')
    n=$(echo "$symbolic_output" | awk '/n:/ {print $2}')
    P_nnz=$(echo "$symbolic_output" | awk '/P.nnz/ {print $3}')
    L_nnz=$(echo "$symbolic_output" | awk '/L.nnz/ {print $3}')
    L_D_nnz=$(echo "$symbolic_output" | awk '/L_D.nnz/ {print $3}')

    echo "$subdiv,$n,$P_nnz,$L_nnz,$L_D_nnz" >> $OUT_SYMBOLIC

    ############################################################
    # CHOLESKY TIMING TEST
    ############################################################
    sum_chol=0
    sum_chol_nested=0
    for ((i=1;i<=RUNS;i++)); do
        chol_output=$($EXEC_CHOLESKY --subdiv $s)

        t_chol=$(echo "$chol_output" | awk '/chol_time:/ {print $2}')
        t_chol_nested=$(echo "$chol_output" | awk '/chol_nested_time:/ {print $2}')

        sum_chol=$(echo "$sum_chol + $t_chol" | bc -l)
        sum_chol_nested=$(echo "$sum_chol_nested + $t_chol_nested" | bc -l)
    done
    avg_chol=$(echo "$sum_chol / $RUNS" | bc -l)
    avg_chol_nested=$(echo "$sum_chol_nested / $RUNS" | bc -l)

    echo "$s,$n,$avg_chol,$avg_chol_nested" >> $OUT_CHOLESKY

    ############################################################
    # NAVIER-STOKES TIMING TEST
    ############################################################

    # CG solver (test_NS) average
    sum_ns=0
    for ((i=1;i<=RUNS;i++)); do
        ns_output=$($EXEC_NS cube $s -b )
        t_ns=$(echo "$ns_output" | grep "Time elapsed" | awk '{print $3}')
        sum_ns=$(echo "$sum_ns + $t_ns" | bc -l)
    done
    avg_ns=$(echo "$sum_ns / $RUNS" | bc -l)

    # Cholesky NS solver (test_navier_stokes_cholesky) average
    sum_chol_ns=0
    for ((i=1;i<=RUNS;i++)); do
        chol_ns_output=$($EXEC_NS_CHOL cube $s -b)
        t_chol_ns=$(echo "$chol_ns_output" | grep "Time elapsed" | awk '{print $3}')
        sum_chol_ns=$(echo "$sum_chol_ns + $t_chol_ns" | bc -l)
    done
    avg_chol_ns=$(echo "$sum_chol_ns / $RUNS" | bc -l)

    echo "$s,$avg_ns,$avg_chol_ns" >> $OUT_NS

done

echo "Done."
echo "Symbolic results -> $OUT_SYMBOLIC"
echo "Cholesky timings -> $OUT_CHOLESKY"
echo "NS timings -> $OUT_NS"

python -m plots