#This file is basically generated by ChatGPT
#!/usr/bin/env zsh

EXEC_SYMBOLIC=./build/release/test_symbolic
EXEC_CHOLESKY=./build/release/test_cholesky
EXEC_NS=./build/release/test_NS
EXEC_NS_CHOL=./build/release/test_navier_stokes_cholesky

OUT_SYMBOLIC=sparsity_results.csv
OUT_CHOLESKY=cholesky_timings.csv
OUT_NS=NS_timings.csv

START=2
END=20

echo "subdiv,n,P_nnz,L_nnz,L_D_nnz" > $OUT_SYMBOLIC
echo "subdiv,n,chol_time_avg,chol_nested_time_avg" > $OUT_CHOLESKY
echo "subdiv,ns_time_avg,cholesky_time_avg" > $OUT_NS

for ((s=$START; s<=$END; s++)); do
    echo "Running subdiv=$s"

    ############################################################
    # SYMBOLIC TEST (no timing needed)
    ############################################################
    symbolic_output=$($EXEC_SYMBOLIC -s $s)

    subdiv=$(echo "$symbolic_output" | awk '/subdiv:/ {print $2}')
    n=$(echo "$symbolic_output" | awk '/n:/ {print $2}')
    P_nnz=$(echo "$symbolic_output" | awk '/P.nnz/ {print $3}')
    L_nnz=$(echo "$symbolic_output" | awk '/L.nnz/ {print $3}')
    L_D_nnz=$(echo "$symbolic_output" | awk '/L_D.nnz/ {print $3}')

    echo "$subdiv,$n,$P_nnz,$L_nnz,$L_D_nnz" >> $OUT_SYMBOLIC

    ############################################################
    # CHOLESKY TIMING TEST
    ############################################################

    chol_output=$($EXEC_CHOLESKY --subdiv $s)

    t_chol=$(echo "$chol_output" | awk '/chol_time:/ {print $2}')
    t_chol_nested=$(echo "$chol_output" | awk '/chol_nested_time:/ {print $2}')


    echo "$s,$n,$t_chol,$t_chol_nested" >> $OUT_CHOLESKY

    ############################################################
    # NAVIER-STOKES TIMING TEST
    ############################################################

    # CG solver (test_NS) average

    ns_output=$($EXEC_NS cube $s -b )
    t_ns=$(echo "$ns_output" | grep "Time elapsed" | awk '{print $3}')
        

    # Cholesky NS solver (test_navier_stokes_cholesky) average
    
    chol_ns_output=$($EXEC_NS_CHOL cube $s -b)
    t_chol_ns=$(echo "$chol_ns_output" | grep "Time elapsed" | awk '{print $3}')

    echo "$s,$t_ns,$t_chol_ns" >> $OUT_NS

done

echo "Done."
echo "Symbolic results -> $OUT_SYMBOLIC"
echo "Cholesky timings -> $OUT_CHOLESKY"
echo "NS timings -> $OUT_NS"

python projects/utils/plots.py